name: livres
description: "Application de gestion de biblioth√®que avec Firebase"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  firebase_core:
  cloud_firestore:
  firebase_storage:
  image_picker:
  cached_network_image:
  uuid:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  flutter_launcher_icons:

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"
  min_sdk_android: 23

flutter:
  uses-material-design: true
  
  assets:
    - assets/
